USE [master]
GO
/****** Object:  Database [Owt]    Script Date: 11/10/2020 13:35:43 ******/
CREATE DATABASE [Owt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Owt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.APPSERVERSQL01\MSSQL\DATA\Owt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Owt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.APPSERVERSQL01\MSSQL\DATA\Owt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Owt] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Owt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Owt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Owt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Owt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Owt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Owt] SET ARITHABORT OFF 
GO
ALTER DATABASE [Owt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Owt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Owt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Owt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Owt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Owt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Owt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Owt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Owt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Owt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Owt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Owt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Owt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Owt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Owt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Owt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Owt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Owt] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Owt] SET  MULTI_USER 
GO
ALTER DATABASE [Owt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Owt] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Owt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Owt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Owt] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Owt', N'ON'
GO
ALTER DATABASE [Owt] SET QUERY_STORE = OFF
GO
USE [Owt]
GO
/****** Object:  User [OwtUser]    Script Date: 11/10/2020 13:35:43 ******/
CREATE USER [OwtUser] FOR LOGIN [OwtUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [OwtUser]
GO
/****** Object:  Schema [cfg]    Script Date: 11/10/2020 13:35:43 ******/
CREATE SCHEMA [cfg]
GO
/****** Object:  Schema [op]    Script Date: 11/10/2020 13:35:43 ******/
CREATE SCHEMA [op]
GO
/****** Object:  Table [cfg].[ExpertiseLevels]    Script Date: 11/10/2020 13:35:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [cfg].[ExpertiseLevels](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Deleted] [bit] NOT NULL,
 CONSTRAINT [PK_ExpertiseLevels] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [cfg].[Skills]    Script Date: 11/10/2020 13:35:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [cfg].[Skills](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Deleted] [bit] NOT NULL,
 CONSTRAINT [PK_Skills] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [op].[Contacts]    Script Date: 11/10/2020 13:35:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [op].[Contacts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Firstname] [nvarchar](255) NULL,
	[Lastname] [nvarchar](255) NULL,
	[Address] [nvarchar](512) NULL,
	[Email] [nvarchar](512) NULL,
	[MobilePhoneNumber] [nvarchar](512) NULL,
	[Deleted] [bit] NOT NULL,
	[CreatedBy] [nvarchar](1024) NOT NULL,
 CONSTRAINT [PK_op.Contacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [op].[ContactsSkills]    Script Date: 11/10/2020 13:35:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [op].[ContactsSkills](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ContactId] [int] NOT NULL,
	[SkillId] [int] NOT NULL,
	[ExpertiseLevelId] [int] NOT NULL,
	[Deleted] [bit] NOT NULL,
	[CreatedBy] [nvarchar](1024) NOT NULL,
 CONSTRAINT [PK_ContactsSkills] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [cfg].[ExpertiseLevels] ON 
GO
INSERT [cfg].[ExpertiseLevels] ([Id], [Name], [Deleted]) VALUES (2, N'E1', 0)
GO
INSERT [cfg].[ExpertiseLevels] ([Id], [Name], [Deleted]) VALUES (3, N'Senior2', 0)
GO
SET IDENTITY_INSERT [cfg].[ExpertiseLevels] OFF
GO
SET IDENTITY_INSERT [cfg].[Skills] ON 
GO
INSERT [cfg].[Skills] ([Id], [Name], [Deleted]) VALUES (1, N'Skill 1', 0)
GO
INSERT [cfg].[Skills] ([Id], [Name], [Deleted]) VALUES (2, N'skill 2', 0)
GO
SET IDENTITY_INSERT [cfg].[Skills] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_ExpertiseLevels_Name]    Script Date: 11/10/2020 13:35:43 ******/
ALTER TABLE [cfg].[ExpertiseLevels] ADD  CONSTRAINT [UX_ExpertiseLevels_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_Skills_Name]    Script Date: 11/10/2020 13:35:43 ******/
ALTER TABLE [cfg].[Skills] ADD  CONSTRAINT [UX_Skills_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [cfg].[ExpertiseLevels] ADD  CONSTRAINT [DF_ExpertiseLevels_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
ALTER TABLE [cfg].[Skills] ADD  CONSTRAINT [DF_Skills_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
ALTER TABLE [op].[Contacts] ADD  CONSTRAINT [DF_Contacts_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
ALTER TABLE [op].[ContactsSkills] ADD  CONSTRAINT [DF_ContactsSkills_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO
ALTER TABLE [op].[ContactsSkills]  WITH CHECK ADD  CONSTRAINT [FK_ContactsSkills_Contacts] FOREIGN KEY([ContactId])
REFERENCES [op].[Contacts] ([Id])
GO
ALTER TABLE [op].[ContactsSkills] CHECK CONSTRAINT [FK_ContactsSkills_Contacts]
GO
ALTER TABLE [op].[ContactsSkills]  WITH CHECK ADD  CONSTRAINT [FK_ContactsSkills_ExpertiseLevels] FOREIGN KEY([ExpertiseLevelId])
REFERENCES [cfg].[ExpertiseLevels] ([Id])
GO
ALTER TABLE [op].[ContactsSkills] CHECK CONSTRAINT [FK_ContactsSkills_ExpertiseLevels]
GO
ALTER TABLE [op].[ContactsSkills]  WITH CHECK ADD  CONSTRAINT [FK_ContactsSkills_Skills] FOREIGN KEY([SkillId])
REFERENCES [cfg].[Skills] ([Id])
GO
ALTER TABLE [op].[ContactsSkills] CHECK CONSTRAINT [FK_ContactsSkills_Skills]
GO
USE [master]
GO
ALTER DATABASE [Owt] SET  READ_WRITE 
GO
